Sir Don Bradman (Australia) Sachin Tendulkar (India) Sir Garfield Sobers (West Indies)
Imran Khan (Pakistan)
Sir Ian Botham (England)
Shane Warne (Australia)
Sir Viv Richards (West Indies)
Brian Lara (West Indies)
Jaques Kallis (South Africa)
MS Dhoni (India)
